CREATE ROLE crm_role NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE crm_user LOGIN PASSWORD 'crm_user' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT crm_role TO crm_user;

